### ISSUE TITLE
conditional className={styles.foo}

### ISSUE THREAD

**Issue by rotegras** [rotegras/shopping-app#4]
Hallo Johannes. @jkettmann 
feature/sortupdown
index.js + controls.js

Eine neue Frage. Es funktioniert jetzt alles, up und down ordnen. Ich will aber jetzt conditional classes erstellen, was mit className={styles.classname} schaffe ich nicht.

in index.js:
<ul className={ styles.sortclasses }>
          {buttons.map((button, index) =>( 
            <Controls 
              key={index}
              name={button.name}
              checkedClass={button.name == this.state.sortBy ? 'arrow': 'noarrow'}
              checked={button.name == this.state.sortBy ? true : false}
              action={this.reorder}
            />
        ))}
        </ul>
....

in Controls.js
const Controls = ({name, checked, **checkedClass**, action}) => {
  
  const callBack = (name) => {
    action(name); 
    console.log(name);
  }

  return(
    <li className={ styles.li }> 
      <span className={styles.**checkedClass**}> // ich habe auch was ahnliches wie {styles. + ...
....
Gibt es eine einfache Lösung oder besser einen weiteren Metode verwenden?

Vielen Dank

**Comment by jkettmann** [comment]
Im Moment gibst du `checkedClass` als string an `Controls`. Dort setzt du aber `className={styles.checkedClass}`. D.h. in `controls.css` muss es eine Klasse `checkedClass` geben, die gibt es aber nicht. Außerdem hat das `checkedClass` prop die Werte `arrow` oder `noarrow`. Diese Klassen gibt es in `css` auch nicht.

Ich würde `checkedClass` nicht als prop an `Controls` geben, sondern nur `checked`. In `controls.js` kannst du dann über `className={checked ? styles.arrow : styles.noarrow}` dynamisch die css Klasse setzen. Dafür müssen aber natürlich die Klassen `arrow` und `noarrow` im css existieren ;-)

Hat das geholfen?

**Comment by rotegras** [comment]
Super! Ja, hat geholfen, genau das wollte ich machen, und dann alles mögliche probiert, dann draussen vom Component usw.
Danke
